name: Pipeline GitHub
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install
      - name: Install pandas
        run: pip install pandas

      - name: Install sklearn
        run: pip install sklearn

      - name: Install pytest
        run: pip install pytest

      - name: Install Jinja2
        run: pip install --upgrade jinja2

      - name: Install streamlit
        run: pip install streamlit

      - name: Install npm
        run: sudo apt install nodejs npm

      - name: Install cypress
        run: npm install cypress --save-dev

      - name: ls
        run: ls

      # Modele
      - name: Modèless
        run: python mldash-main/build_model.py

      - name: lancement application streamlit
        run: streamlit run mldash-main/model_dashborad.py

      # Test
      - name: Test unitaires
        run: python -m pytest mldash-main/test_model.py

      - name: Cypress run
        uses: cypress-io/github-action@v4
        
