# This is a basic workflow to help you get started with Actions

name: CI
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install
      - name: Install 
        run: apt-get update
        run: apt-get install python3 -y
        run: apt-get install python3-pip -y


