# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]

jobs:
  runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install
      - name: Install pandas
        run: pip install pandas

      - name: Install sklearn
        run: pip install sklearn

      - name: Install pytest
        run: pip install pytest

      - name: Install streamlit
        run: pip install streamlit

      #- name: Install Jinja2
        #run: pip install jinja2

      # Modele
      - name: Modèless
        run: python mldash-main/build_model.py

      # Modele
      - name: Test unitaires
        run: python -m pytest mldash-main/test_model.py
